[build]
  command = "npm install --force && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NPM_FLAGS = "--force"
  NODE_VERSION = "18.20.6"
